// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvsgotjipcmqbotwpwoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2c2dvdGppcGNtcWJvdHdwd29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTg3NDEsImV4cCI6MjA2MTE3NDc0MX0.09RzqO28atvlyyqB9qg0BLixWIs939DMIaUAcOcRdIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);